### ISSUE TITLE
Session Bug - 無帳號登入

### ISSUE THREAD

**Issue by Benny1923** [s3131212/allendisk#3]
在同一伺服器中
先登入LTAYER，再開啟AllenDisk
會發生AllenDisk跳過登入前主頁面，直接進入檔案管理頁面
推估是Session名稱重複
還在想解決方案

**Comment by s3131212** [comment]
是 Session 名稱重複導致的，大概只能把名稱改掉吧，下一版會在 Session 加上前綴的，謝謝通報

**Comment by s3131212** [comment]
等 bug 修好再 close 啦 XD

**Comment by Benny1923** [comment]
My bad sorry = =||

**Comment by s3131212** [comment]
已經在 1.6 版修好囉 :)
d3f80cd
