### ISSUE TITLE
下載頁面上面出現這兩串~~

### ISSUE THREAD

**Issue by ww550669** [s3131212/allendisk#6]
Warning: set_time_limit() has been disabled for security reasons in /home/snowdrive/public_html/downfile.php on line 10

Warning: Cannot modify header information - headers already sent by (output started at /home/snowdrive/public_html/downfile.php:10) in /home/snowdrive/public_html/downfile.php on line 31

下載頁面上面出現這兩串~~

**Comment by Benny1923** [comment]
估計是php的功能(function)被禁用和等待時間太短
把php.ini中的:
max_execution_time的值調整大一點(單位:秒,建議30~60之間) ex.max_execution_time = 30
還有output_buffering的值調整為On應該就正常了ex. output_bufferin = On
希望能幫到你

**Comment by s3131212** [comment]
啊這是蠢 Bug ，幾天後就會把 Patch 放上去囉，感謝通報
